name: Build Linux Executable

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   run: pipx install poetry

            -   uses: actions/setup-python@v5
                with:
                    python-version: '3.10'
                    cache: 'poetry'

            -   run: poetry install

            -   run: |
                    git clone https://github.com/tulip-control/dd.git dd-git
                    cd dd-git
                    python setup.py install --fetch --cudd --cudd_zdd
                    cd ..
                    
            -   run: poetry run python -m nuitka bddc.py

            -   uses: actions/upload-artifact@v4
                with:
                    path: '*.bin'

