name: Build Executables

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}

        steps:
            -   uses: actions/checkout@v4

            -   uses: actions/setup-python@v5
                with:
                    python-version: "3.10"

            -   uses: abatilo/actions-poetry@v2

            -   run: poetry install

            -   name: Build Executable
                uses: Nuitka/Nuitka-Action@main
                with:
                    nuitka-version: main
                    script-name: bddc.py

            -   uses: actions/upload-artifact@v4
                with:
                    name: ${{ runner.os }} Build
                    path: |
                        build/*.exe
                        build/*.bin
                        build/*.app/**/*

