name: Build Executables

on:
    push:
        branches:
            - main

jobs:
    build:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}

        steps:
            -   uses: actions/checkout@v4

            -   uses: actions/setup-python@v4
                with:
                    python-version: "3.10"

            -   uses: abatilo/actions-poetry@v2

            -   run: poetry install

            -   run: poetry run nuitka3 bddc.py

            -   uses: actions/upload-artifact@v3
                with:
                    name: bddc
                    path: |
                        build/*.exe
                        build/*.bin
                        build/*.app/**/*

